/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    404: typeof import('./src/components/404.vue')['default']
    404Page: typeof import('./src/components/404Page.vue')['default']
    Account: typeof import('./src/components/Account.vue')['default']
    BalanceManagement: typeof import('./src/components/account/BalanceManagement.vue')['default']
    BalanceMangement: typeof import('./src/components/account/BalanceMangement.vue')['default']
    BlanceMangement: typeof import('./src/components/account/BlanceMangement.vue')['default']
    DeviceList: typeof import('./src/components/DeviceList.vue')['default']
    DevicePanel: typeof import('./src/components/DevicePanel.vue')['default']
    DutyCycleProfile: typeof import('./src/components/profile/DutyCycleProfile.vue')['default']
    ExpenseRecord: typeof import('./src/components/account/ExpenseRecord.vue')['default']
    GeneralProfile: typeof import('./src/components/profile/GeneralProfile.vue')['default']
    HeaterProfile: typeof import('./src/components/profile/HeaterProfile.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Home: typeof import('./src/components/Home.vue')['default']
    LabelList: typeof import('./src/components/LabelList.vue')['default']
    LabelPanel: typeof import('./src/components/LabelPanel.vue')['default']
    Login: typeof import('./src/components/Login.vue')['default']
    PageNotFound: typeof import('./src/components/PageNotFound.vue')['default']
    Profile: typeof import('./src/components/Profile.vue')['default']
    Register: typeof import('./src/components/Register.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ServerDetail: typeof import('./src/components/ServerDetail.vue')['default']
    ServerList: typeof import('./src/components/ServerList.vue')['default']
    ServerOrder: typeof import('./src/components/ServerOrder.vue')['default']
    ServerPanel: typeof import('./src/components/ServerPanel.vue')['default']
    Test: typeof import('./src/components/test.vue')['default']
    TopBar: typeof import('./src/components/TopBar.vue')['default']
    UserInfo: typeof import('./src/components/account/UserInfo.vue')['default']
  }
}
